In [ ]:
import numpy as np
def mean_and_variance(vector):
    mean = np.mean(vector)
    variance = np.var(vector)
    return mean, variance
N = 10
vector = np.random.rand(N)
mean, variance = mean_and_variance(vector)
print("Vector (1xN):", vector)
print("Mean of the vector:", mean)
print("Variance of the vector:", variance)
# Mean: The mean of the sample represents the average value of all the features in the vector.
#       It gives a central value that summarizes the overall tendency of the features.
# Variance: The variance represents the spread or dispersion of the feature values around the mean.
#           A higher variance indicates that the feature values are more spread out, while a lower variance
#           indicates that they are closer to the mean.



Vector (1xN): [0.87602926 0.01112755 0.08222527 0.09074826 0.91670093 0.04768003
 0.94045972 0.00315849 0.78950339 0.63346994]
Mean of the vector: 0.4391102842522102
Variance of the vector: 0.16060571275577104


In [ ]:
import numpy as np

def compute_covariance(vector1, vector2):

    covariance_matrix = np.cov(vector1, vector2)
    covariance = covariance_matrix[0, 1]
    return covariance
M = 10
vector1 = np.random.rand(M)
vector2 = np.random.rand(M)
covariance = compute_covariance(vector1, vector2)
print("Vector 1 (1xM):", vector1)
print("Vector 2 (1xM):", vector2)
print("Covariance between Vector 1 and Vector 2:", covariance)
# Covariance: The covariance between two vectors measures how much the two vectors vary together.
#             A positive covariance indicates that as one vector increases, the other tends to increase as well.
#             A negative covariance indicates that as one vector increases, the other tends to decrease.
#             If the covariance is close to zero, it suggests that the vectors are not linearly related.


Vector 1 (1xM): [0.53660981 0.99994573 0.09091951 0.2545822  0.75100358 0.10555861
 0.140247   0.20429652 0.4482209  0.43098376]
Vector 2 (1xM): [0.07482508 0.64362894 0.89833075 0.69135692 0.24461311 0.44876568
 0.00299044 0.86109054 0.96159558 0.95885862]
Covariance between Vector 1 and Vector 2: -0.011060642841606991


In [ ]:
import numpy as np

def compute_correlation(vector1, vector2):
    correlation_matrix = np.corrcoef(vector1, vector2)
    correlation = correlation_matrix[0, 1]
    return correlation

N = 10
vector1 = np.random.rand(N)
vector2 = np.random.rand(N)
correlation = compute_correlation(vector1, vector2)

print("Vector 1 (1xN):", vector1)
print("Vector 2 (1xN):", vector2)
print("Correlation between Vector 1 and Vector 2:", correlation)

# Correlation: The correlation between two vectors measures the strength and direction of their linear relationship.
#              It ranges from -1 to 1:
#               1 indicates a perfect positive linear relationship.
#              -1 indicates a perfect negative linear relationship.
#               0 indicates no linear relationship.


Vector 1 (1xN): [0.55005263 0.35678212 0.93193224 0.13601356 0.50149363 0.39248854
 0.95185797 0.58028979 0.14571516 0.55548841]
Vector 2 (1xN): [0.40138406 0.05972904 0.5791281  0.47890127 0.4228893  0.80201175
 0.02650923 0.99113309 0.7226346  0.09771186]
Correlation between Vector 1 and Vector 2: -0.24951590631150256


In [ ]:
import numpy as np
def compute_covariance_matrix(matrix):

    covariance_matrix = np.cov(matrix, rowvar=True)
    return covariance_matrix

def compute_correlation_matrix(matrix):

    correlation_matrix = np.corrcoef(matrix, rowvar=True)
    return correlation_matrix
M = 5
N = 10
matrix = np.random.rand(M, N)
covariance_matrix = compute_covariance_matrix(matrix)
correlation_matrix = compute_correlation_matrix(matrix)
print("Matrix (MxN):\n", matrix)
print("\nCovariance Matrix (MxM):\n", covariance_matrix)
print("\nCorrelation Matrix (MxM):\n", correlation_matrix)

# Covariance Matrix: The covariance matrix shows the covariance between each pair of features.
#                   The (i,j) entry of the matrix represents the covariance between the ith and jth features.
#                   A positive value indicates that the two features increase together,
#                   while a negative value indicates that as one feature increases, the other tends to decrease.
#
# Correlation Matrix: The correlation matrix normalizes the covariance matrix to provide a scale-free measure of the
#                     linear relationship between features. The values range from -1 to 1.
#                     A value of 1 indicates a perfect positive linear relationship, -1 indicates a perfect negative
#                     linear relationship, and 0 indicates no linear relationship.


Matrix (MxN):
 [[0.54491542 0.9076413  0.95123671 0.38895261 0.16985938 0.376444
  0.52054317 0.60035512 0.26656511 0.20767602]
 [0.57308893 0.75537606 0.58026768 0.07257408 0.69465788 0.55645983
  0.20405625 0.50528969 0.41310071 0.90897137]
 [0.89855503 0.86707517 0.92810294 0.54779677 0.37496998 0.27487758
  0.16668617 0.49779653 0.97293059 0.87057786]
 [0.00480813 0.41172449 0.37146675 0.83449701 0.45533264 0.40795011
  0.16633521 0.81920277 0.63911883 0.74554833]
 [0.96266664 0.10104731 0.74827642 0.18457408 0.1256745  0.44944897
  0.88971443 0.94637315 0.45696682 0.88180286]]

Covariance Matrix (MxM):
 [[ 0.07315545  0.00186103  0.02310119 -0.02303046  0.01013179]
 [ 0.00186103  0.06180362  0.03021384 -0.00370568  0.00424219]
 [ 0.02310119  0.03021384  0.0913034   0.00499532  0.00812579]
 [-0.02303046 -0.00370568  0.00499532  0.0758535  -0.02210813]
 [ 0.01013179  0.00424219  0.00812579 -0.02210813  0.12445022]]

Correlation Matrix (MxM):
 [[ 1.          0.02767726  0.28266206 -0